//Idle Sessions
let TimeSlice = 5min;
InsightsMetrics
| where Name =='pg_stat_activity_count' and Val != 0
| extend Tags = parse_json(Tags)
| project Computer, Val, TimeGenerated,Server = tostring(Tags.server), DatabaseName = tostring(Tags.datname),DatID = tostring(Tags.datid),Name, State =  tostring(Tags.state)
| where State in ('idle','idle in transaction','idle in transaction')
| summarize avg = avg(Val),max = max(Val),sum=sum(Val) by Computer,Name,Server,DatabaseName,DatID, State,bin(TimeGenerated, TimeSlice)
