//Number of rows fetched by queries
let DatabaseName = 'postgres';
InsightsMetrics
| where Name == 'pg_stat_database_tup_fetched'
| extend Tags = parse_json(Tags)
| project  Database = tostring(Tags.datname), Name, Val , ClusterName = tostring(Tags.["container.azm.ms/clusterName"]), Server = tostring(Tags.server)
| where Database == DatabaseName
| summarize Sum = sum(Val) by ClusterName,Name,Server,Database
